[project]
name = "code-metircs-mlapi"
version = "0.0.0"
description = "Machine Learning API to support Code Metrics"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.110.2",
    "numpy==1.26.4",
    "pandas>=2.2.3",
    "pmdarima>=2.0.4",
    "pydantic>=2.11.3",
    "scikit-learn>=1.6.1",
    "statsmodels>=0.14.4",
    "uvicorn>=0.34.2",
]

[project.optional-dependencies]
build = [
    "build",
    "setuptools",
    "wheel"
    ]

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pytest>=8.3.5",
]

[build-system]
requires = ["setuptools>=75"]
build-backend = "setuptools.build_meta"

[project.urls]
Homepage = "https://github.com/DeloitteDigitalUK/code-metrics"
Issues = "https://github.com/DeloitteDigitalUK/code-metrics/issues"
Docs = "https://code-metrics-project.github.io/docs/"

[tool.black]
line-length = 160
target-version = ['py312', 'py313']
include = '\.pyi?$'

[project.scripts]
mlapi = "mlapi.main:main"