{{- define "mock-api.application" -}}
- name: {{ .Chart.Name }}-mocks
  securityContext:
    {{- toYaml .Values.application.securityContext | nindent 12 }}
  image: "{{ .Values.application.image.repository }}:{{ .Values.application.image.tag | default .Chart.AppVersion }}"
  imagePullPolicy: {{ .Values.application.image.pullPolicy }}
  env:
  {{- range $key := .Values.application.envVars.templates }}
  - name: {{ $key }}
    value: {{ include $key $ }}
  {{- end }}
  {{- range $key, $val := .Values.application.envVars.keyValues }}
  - name: {{ $key }}
    value: {{ $val | quote }}
  {{- end }}
  {{- range $k, $v :=  .Values.application.envVars.secrets }}
  - name: {{ $k }}
    valueFrom:
      secretKeyRef:
        key: {{ $v.key }}
        name: {{ $v.name }}
  {{- end }}
  ports:
    - name: http
      containerPort: {{ .Values.application.port }}
      protocol: TCP
  livenessProbe:
    httpGet:
      path: /system/status
      port: http
  readinessProbe:
    httpGet:
      path: /system/status
      port: http
  resources:
    {{- toYaml .Values.application.resources | nindent 12 }}
  {{- end -}}