import {
  Activity,
  Anchor,
  Atom,
  BarChart3,
  Bell,
  BookOpen,
  Bot,
  Box,
  Boxes,
  Brain,
  Briefcase,
  Bug,
  Building2,
  Bus,
  Calculator,
  Calendar,
  Camera,
  Car,
  CarFront,
  ChartBar,
  ChartLine,
  Check,
  Circle,
  Clock,
  Cloud,
  CloudCog,
  CloudLightning,
  Code,
  Code2,
  Coffee,
  Container,
  Cpu,
  CreditCard,
  Database,
  DatabaseZap,
  DollarSign,
  Droplets,
  Factory,
  FileText,
  Film,
  Flame,
  Folder,
  Gamepad2,
  Gauge,
  Gem,
  GitBranch,
  GitFork,
  Globe,
  GraduationCap,
  HardDrive,
  Hammer,
  Headset,
  Heart,
  Hexagon,
  Home,
  Key,
  Laptop,
  Layers,
  Landmark,
  Leaf,
  Lightbulb,
  LineChart,
  Lock,
  Mail,
  MessageSquare,
  Monitor,
  Moon,
  Music,
  Network,
  Package,
  Percent,
  Phone,
  PieChart,
  Plane,
  Rocket,
  Server,
  ServerCog,
  Settings,
  Shield,
  ShieldCheck,
  Ship,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Square,
  Star,
  Sun,
  Tablet,
  Target,
  Terminal,
  Thermometer,
  Timer,
  TrainFront,
  TrendingDown,
  TrendingUp,
  Triangle,
  Trophy,
  Truck,
  Wallet,
  Wifi,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

const workloadIcons: Record<string, LucideIcon> = {
  activity: Activity,
  anchor: Anchor,
  atom: Atom,
  "bar-chart-3": BarChart3,
  bell: Bell,
  "book-open": BookOpen,
  bot: Bot,
  box: Box,
  boxes: Boxes,
  brain: Brain,
  briefcase: Briefcase,
  bug: Bug,
  "building-2": Building2,
  bus: Bus,
  calculator: Calculator,
  calendar: Calendar,
  camera: Camera,
  car: Car,
  "car-front": CarFront,
  "chart-bar": ChartBar,
  "chart-line": ChartLine,
  check: Check,
  circle: Circle,
  clock: Clock,
  cloud: Cloud,
  "cloud-cog": CloudCog,
  "cloud-lightning": CloudLightning,
  code: Code,
  "code-2": Code2,
  coffee: Coffee,
  container: Container,
  cpu: Cpu,
  "credit-card": CreditCard,
  database: Database,
  "database-zap": DatabaseZap,
  "dollar-sign": DollarSign,
  droplets: Droplets,
  factory: Factory,
  "file-text": FileText,
  film: Film,
  flame: Flame,
  folder: Folder,
  "gamepad-2": Gamepad2,
  gauge: Gauge,
  gem: Gem,
  "git-branch": GitBranch,
  "git-fork": GitFork,
  globe: Globe,
  "graduation-cap": GraduationCap,
  "hard-drive": HardDrive,
  hammer: Hammer,
  headset: Headset,
  heart: Heart,
  hexagon: Hexagon,
  home: Home,
  key: Key,
  laptop: Laptop,
  layers: Layers,
  landmark: Landmark,
  leaf: Leaf,
  lightbulb: Lightbulb,
  "line-chart": LineChart,
  lock: Lock,
  mail: Mail,
  "message-square": MessageSquare,
  monitor: Monitor,
  moon: Moon,
  music: Music,
  network: Network,
  package: Package,
  percent: Percent,
  phone: Phone,
  "pie-chart": PieChart,
  plane: Plane,
  rocket: Rocket,
  server: Server,
  "server-cog": ServerCog,
  settings: Settings,
  shield: Shield,
  "shield-check": ShieldCheck,
  ship: Ship,
  "shopping-bag": ShoppingBag,
  "shopping-cart": ShoppingCart,
  smartphone: Smartphone,
  sparkles: Sparkles,
  square: Square,
  star: Star,
  sun: Sun,
  tablet: Tablet,
  target: Target,
  terminal: Terminal,
  thermometer: Thermometer,
  timer: Timer,
  "train-front": TrainFront,
  "trending-down": TrendingDown,
  "trending-up": TrendingUp,
  triangle: Triangle,
  trophy: Trophy,
  truck: Truck,
  wallet: Wallet,
  wifi: Wifi,
  wrench: Wrench,
  zap: Zap,
};

export const WORKLOAD_ICON_NAMES = Object.keys(workloadIcons).sort();

export interface WorkloadIconProps {
  icon?: string;
  color: string;
  className?: string;
}

export function WorkloadIcon({ icon, color, className }: WorkloadIconProps) {
  const Icon = (icon && workloadIcons[icon.toLowerCase()]) || Circle;
  return <Icon className={className} style={{ color }} fill={Icon === Circle ? color : "none"} />;
}
