apiVersion: v2
name: code-metrics-demo
description: The CodeMetrics tool supporting integrations for demos and testing
kubeVersion: '>=1.17-0'
type: application
version: 1.0.0
appVersion: "5.0.0"

dependencies:
- name: jenkins
  version: '*.*.*'
  condition: jenkins.enabled
- name: mock-api
  version: '*.*.*'
  condition: mock-api.enabled
- name: openldap-stack-ha
  alias: openldap
  repository: https://jp-gouin.github.io/helm-openldap/
  version: '4.2.1'
  condition: openldap.enabled
- name: keycloak
  repository: https://codecentric.github.io/helm-charts
  version: '18.4.4'
  condition: keycloak.enabled
