plugin: rest

system:
  stores:
    bugs:
      preloadFile: "historic/bugs.json"

resources:
# Health check endpoint for connection checker
- path: /rest/api/2/serverInfo
  method: get
  response:
    statusCode: 200
    content: |
      { "baseUrl": "http://mocks:8080", "version": "9.0.0", "versionNumbers": [9, 0, 0], "serverTitle": "Mock Jira" }

# Deprecated endpoint
- path: /rest/api/2/search
  method: get
  response:
    scriptFile: search.js

# Currently supported endpoint
- path: /rest/api/3/search/jql
  method: get
  response:
    scriptFile: search.js
