ARG IMGREPO=""
FROM ${IMGREPO}node:lts AS deps
WORKDIR /app
COPY promosite/package*.json ./
RUN npm install

FROM ${IMGREPO}node:lts AS build
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY promosite/ .
RUN npm run build

FROM ${IMGREPO}nginx:stable-alpine AS deploy
COPY --from=build /app/dist /usr/share/nginx/html
COPY promosite/nginx/nginx.conf /etc/nginx/nginx.conf

EXPOSE 8080
