ARG IMGREPO=""
FROM ${IMGREPO}node:lts AS build

# INSTALL; separate from build to benefit from Docker cache
WORKDIR /usr/src/app/frontend
RUN npm install -g bun
COPY package.json bun.lock ./
RUN --mount=type=cache,target=/root/.bun/install/cache bun install --frozen-lockfile

# BUILD
COPY . ./
RUN bun run build-only


FROM ${IMGREPO}nginx AS run

LABEL org.opencontainers.image.source=https://github.com/code-metrics-project/releases

ENV API_BASE_URL="http://localhost:3000"

# Copy built files
COPY --from=build /usr/src/app/frontend/dist /usr/share/nginx/html
COPY ./files/nginx.conf /etc/nginx/conf.d/default.conf
COPY ./files/write-config.sh /docker-entrypoint.d/write-config.sh
RUN chmod +x /docker-entrypoint.d/write-config.sh
