engine: golang
version: 5.17.1
startTimeout: 60

env:
  # we use 'scriptFile' (rather than steps) and 'logger.x' (rather than console.x) in our mocks
  IMPOSTER_SUPPORT_LEGACY_CONFIG: true

cli:
  version: 1.3.3

default:
  # List of plugins to install
  # See https://github.com/imposter-project/imposter-go-plugins/releases
  plugins:
    - oidc-server
