{{- if and .Values.databaseSecret.user .Values.databaseSecret.password }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "mongodb.fullname" . }}-users
data:
  username: {{ .Values.databaseSecret.user | b64enc | quote }}
  password: {{ .Values.databaseSecret.password | b64enc | quote }}
{{- end}}
