apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "code-metrics-api.fullname" . }}
data:
  remote-config.yaml: |
    {{- .Values.config.remoteConfig | toYaml | nindent 4 }}

  workload-config.yaml: |
    {{- .Values.config.workloadConfig | toYaml | nindent 4 }}
