{{- if .Values.auth.fromFile }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "code-metrics-api.fullname" . }}-users
data:
  users.json: {{ .Values.secrets.users | toJson | b64enc | quote }}
{{- end}}