# This file is additive to the main docker-compose.yaml
#
# To start CodeMetrics using mocked services, run Compose from the
# root directory of the project as follows:
#
# docker-compose -f compose/docker-compose.yaml -f compose/docker-compose-mocks.yaml --project-directory . up --build

services:
  api:
    depends_on:
      mocks:
        condition: service_started
    environment:
      AUTHENTICATOR_IMPL: file
      ACCESS_TOKEN_SECRET: changeme
      ACCESS_TOKEN_TTL: 10m
      REFRESH_TOKEN_TTL: 60m
      LOG_LEVEL: "1"
      LOOKUP_CACHE_ENABLED: "true"
      DATASTORE_IMPL: mongodb
      DATABASE_URI: mongodb://code-metrics:changeme@db:27017
      DATABASE_NAME: code-metrics
    volumes:
      - "./mocks/config:/backend/config"

  mocks:
    image: ghcr.io/code-metrics-project/code-metrics-mocks
    build:
      dockerfile: ../docker/Dockerfile.mocks
      context: mocks
    command:
      - "--plugin=openapi"
      - "--plugin=rest"
      - "--configDir=/opt/imposter/config"
      - "--serverUrl=http://mocks:8080"
    volumes:
      - "./mocks:/opt/imposter/config"
    ports:
      - "8080:8080"
