version: '3.3'

services:
  api:
    image: ghcr.io/code-metrics-project/code-metrics-api
    build:
      dockerfile: ../docker/Dockerfile.backend
      context: backend/
    ports:
      - "3000:3000"
    environment:
      CORS_ORIGIN: "http://localhost:3001"
      DATABASE_URI: "mongodb://code-metrics:changeme@db:27017"
    volumes: []
      # uncomment as required
      # - "./backend/.env:/backend/.env"
      # - "./backend/.config:/backend/config"  # NOTE: Expects local folder path of `backend/.config` for mapping into container
      # - "./backend/config/examples/remote-config.yaml.example:/backend/config/remote-config.yaml"
      # - "./backend/config/examples/workload-config.yaml.example:/backend/config/workload-config.yaml"
      # - "./backend/config/examples/users.json.example:/backend/config/users.json"
      # - "./backend/config/examples/queries-config.json.example:/backend/config/queries-config.json"

  ui:
    image: ghcr.io/code-metrics-project/code-metrics-ui
    build:
      dockerfile: ../docker/Dockerfile.ui
      context: ui/
    ports:
      - "3001:80"
    environment:
      API_BASE_URL: "http://localhost:3000"

  db:
    image: mongo:5
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: "code-metrics"
      MONGO_INITDB_ROOT_USERNAME: "code-metrics"
      MONGO_INITDB_ROOT_PASSWORD: "changeme"
    volumes:
      - "metrics-mongo:/data/db"

  docs:
    image: ghcr.io/code-metrics-project/code-metrics-docs
    build:
      dockerfile: docker/Dockerfile.docs
      args:
        DOCSDIR: ../docs
    ports:
      - "8000:8000"

  mlapi:
    image: ghcr.io/code-metrics-project/code-metrics-mlapi
    build:
      dockerfile: ../docker/Dockerfile.machinelearning
      context: machinelearning/
    ports:
      - "8080:8080"

volumes:
  metrics-mongo: {}
