---
version: "2.0"

workloads:
  - id: athena
    name: "Athena"
    tags:
        department: sales
    codeManagement:
      type: azure
      serverId: mock-azure
      projectName: athena
      repoGroups:
        backend:
          components:
            - repo: /spring-.*/
        frontend:
          sonarTags:
            - fe
        platform:
          components:
            - repo: /.*_platform/
            - repo: /.*_infrastructure/
        monorepos:
          components:
            - name: web-a
              repo: athena_ui_subject_portal
              paths: ["/web-a"]
            - name: web-b
              repo: athena_ui_subject_portal
              paths: ["/web-b"]
    codeAnalysis:
      type: sonar
      serverId: mock-sonar
      mappings:
        - key: petclinic
          vcsRepoName: spring-petclinic
    pipelines:
      type: azure
      serverId: mock-azure
      projectName: athena
      jobGroups:
        backend:
          jobs:
            - name: /spring-.*/
        frontend:
          jobs:
            - name: fe
        platform:
          jobs:
            - name: /.*_platform/
            - name: /.*_infrastructure/
        monorepos:
          jobs:
            - fromRepoGroup: monorepos
      stages:
        - stageId: azure-deployment-pipeline
    projectManagement:
      type: azure
      serverId: mock-azure
      projectName: ADOMockProject
      team: ADOMock
      ticketTypes:
        - Bug
        - Task
        - User Story
        - Defect
        - Issue
    incidents:
      type: azure
      serverId: mock-azure
      projectName: ADOMockProject
      team: ADOMock name[Dropdown]" in ("Athena")'

  - id: gaia
    name: "Gaia"
    tags:
      department: sales
    codeManagement:
      type: github
      serverId: mock-github
      projectName: gaia
      repoGroups:
        backend:
          components:
            - repo: /hello-world/
              name: octo-backend
              paths: ["/backend"]
        frontend:
          components:
            - repo: /hello-world/
              name: octo-frontend
              paths: ["/frontend"]
        platform:
          components:
            - repo: /hello-world/
              name: octo-platform
              paths: ["/platform"]
    codeAnalysis:
      type: sonar
      serverId: mock-sonar
    pipelines:
      type: github
      serverId: mock-github
      projectName: gaia
      jobGroups:
        backend:
          jobs:
            - name: CI
        frontend:
          jobs:
            - name: Linter
        platform:
          jobs:
            - name: /.+/
            - { name: "Dependabot Updates", exclude: true }
      stages:
        - stageId: github-deployment-pipeline
    projectManagement:
      type: github
      serverId: mock-github
      owner: "octocat"  
      repo: "hello-world"
      stateFilter: "all"
      issueTypes:
        - bug
        - enhancement
        - feature
      labelMapping:
        "priority:high": "High"
        "priority:medium": "Medium"
        "priority:low": "Low"
    incidents:
      type: github
      serverId: mock-github
      owner: octocat
      repo: hello-world
      stateFilter: all
      issueTypes:
        - issue
      labelMapping:
        "priority:high": "High"
        "priority:medium": "Medium"
        "priority:low": "Low"
    qualityGates:
      id: default
      version: "0.1.0"

  - id: icarus
    tags:
      department: finance
    codeManagement:
      type: azure
      serverId: mock-azure
      projectName: icarus
      repoGroups:
        backend:
          components:
            - repo: /spring-.*/
        frontend:
          sonarTags:
            - fe
        platform:
          components:
            - repo: /.*_platform/
            - repo: /.*_infrastructure/
    codeAnalysis:
      type: sonar
      serverId: mock-sonar
      mappings:
        - key: petclinic
          vcsRepoName: spring-petclinic
    pipelines:
      type: azure
      serverId: mock-azure
      projectName: athena
      jobGroups:
        backend:
          jobs:
            - name: /spring-.*/
        frontend:
          jobs:
            - name: fe
        platform:
          jobs:
            - fromRepoGroup: platform
      stages:
        - stageId: azure-deployment-pipeline
    projectManagement:
      type: jira
      serverId: mock-jira
      teamFilterJql: '"Team name[Dropdown]" in ("Icarus")'
      projectName: DEV
      prodFilterJql: '"Project Environment[Dropdown]" = PROD'
    incidents:
      type: servicenow
      serverId: mock-servicenow
      tableName: incident
