---
version: "2.0"

workloads:
- id: athena
  name: "Athena team"
  codeManagement:
    type: azure
    serverId: mock-azure
    projectName: athena
    repoGroups:
      backend:
        components:
        - repo: /spring-.*/
      frontend:
        sonarTags:
        - fe
      platform:
        components:
        - repo: /.*_platform/
        - repo: /.*_infrastructure/
  pipelines:
    type: azure
    serverId: mock-azure
    projectName: athena
    jobGroups:
      backend:
        jobNames:
        - /spring-.*/
      frontend:
        jobNames:
        - fe
      platform:
        jobNames:
        - /.*_platform/
        - /.*_infrastructure/
    stages:
      - stageId: azure-deployment-pipeline
  codeAnalysis:
    type: sonar
    serverId: mock-sonar
    mappings:
      - key: petclinic
        vcsRepoName: spring-petclinic
  projectManagement:
    type: jira
    serverId: mock-jira
    projectName: DEV
    teamFilterJql: '"Team name[Dropdown]" in ("Athena")'
  incidents:
    type: jira
    serverId: mock-jira
    projectName: INCIDENT
    teamFilterJql: '"Team name[Dropdown]" in ("Athena")'

- id: gaia
  codeManagement:
    type: github
    serverId: mock-github
    projectName: gaia
    repoGroups:
      backend:
        components:
          - repo: /octocat.*/
      frontend:
        sonarTags:
          - fe
      platform:
        components:
          - repo: /.*_platform/
          - repo: /.*_infrastructure/
  codeAnalysis:
    type: sonar
    serverId: mock-sonar
  pipelines:
    type: github
    serverId: mock-github
    projectName: gaia
    jobGroups:
      backend:
        jobNames:
          - /.*/
      frontend:
        jobNames:
          - fe
      platform:
        jobNames:
          - /.*_platform/
          - /.*_infrastructure/
    stages:
      - stageId: azure-deployment-pipeline
  projectManagement:
    type: jira
    serverId: mock-jira
    teamFilterJql: '"Team name[Dropdown]" in ("Gaia")'
    projectName: DEV
    prodFilterJql: '"Project Environment[Dropdown]" = PROD'
  incidents:
    type: servicenow
    serverId: mock-servicenow
    tableName: incident
  qualityGates:
    id: default
    version: 0.1.0
