plugin: rest

resources:
  - method: get
    path: /orgs/{org}/issue-types
    response:
      scriptFile: GET-issue-types.js

  - method: get
    path: /orgs/{org}/repos
    response:
      file: GET-repos.json

  - method: get
    path: /orgs/{org}/repos
    queryParams:
      type: 'private'
    response:
      content: "[]"

  - method: get
    path: /repos/{org}/{repo}
    response:
      content: repo.json

  - method: get
    path: /repos/{owner}/{repo}/commits
    response:
      file: GET-commits.json

  - method: get
    path: /repos/{owner}/{repo}/commits/{ref}
    response:
      file: GET-commit.json

  - method: get
    path: /repos/{owner}/{repo}/commits/{commit_sha}/pulls
    response:
      file: GET-commitPulls.json

  - method: get
    path: /repos/{owner}/{repo}/pulls
    response:
      file: GET-pullRequests.json

  - method: get
    path: /repos/{owner}/{repo}/pulls/{pull_number}/commits
    response:
      file: GET-pullRequestCommits.json

  - method: get
    path: /repos/{owner}/{repo}/pulls/{pullId}/files
    response:
      file: GET-files.json

  - method: get
    path: /repos/{owner}/{repo}/actions/workflows
    response:
      file: GET-workflows.json

  - method: get
    path: /repos/{owner}/{repo}/actions/runs
    response:
      file: GET-workflowRuns.json

  - method: get
    path: /repos/{owner}/{repo}/actions/runs/{run_id}
    response:
      file: GET-workflowRun.json
  
  - method: get
    path: /repos/{owner}/{repo}/actions/runs/{run_id}/timing
    response:
      file: GET-workflowTiming.json

  - method: get
    path: /repos/{owner}/{repo}/issues
    response:
      scriptFile: GET-issues.js

  - method: get
    path: /repos/{owner}/{repo}/issues/{issue_number}
    response:
      scriptFile: GET-issue.js

  - method: get
    path: /repos/{owner}/{repo}/contents/{filename}
    response:
      file: GET-contents.txt

  - method: get
    path: /repos/{owner}/{repo}/rulesets
    response:
      file: GET-rules.json

  - method: get
    path: /repos/{owner}/{repo}/rulesets/{rule}
    response:
      file: GET-rule.json

  - method: get
    path: /repos/{owner}/{repo}/branches/{branch}/protection
    response:
      file: GET-branch.json

  - method: get
    path: /repos/{owner}/{repo}/dependabot/alerts
    response:
      file: GET-dependabotAlerts.json
