name: CI
on: [push]
jobs:
  setvars:
    runs-on: ubuntu-latest
    outputs:
      vars: ${{ steps.vars.outputs.vars }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set vars (Python)
        id: vars
        run: |
          if [ "$GITHUB_REPOSITORY" = "DeloitteDigitalUK/code-metrics" ]; then
            python3 ./scripts/set_vars.py
          else
            python3 ./scripts/set_vars.py \
              --set helm=false \
              --set machinelearning=false \
              --set threatmodel=false \
              --set desktop=false \
              --set docker=false
          fi

  validate-config:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    needs: [setvars]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node (backend)
        uses: actions/setup-node@v4
        with:
          node-version-file: "/backend/.nvmrc"
      - name: Install backend config dependencies
        working-directory: backend/config
        run: npm install
      - name: Validate mock config
        run: ./mocks/validate-mock-config.sh

  validate:
    needs: [setvars, validate-config]
    uses: ./.github/workflows/validate.yaml
    with:
      vars: ${{ needs.setvars.outputs.vars }}

  cd:
    needs: [setvars, validate-config, validate]
    uses: ./.github/workflows/cd.yaml
    with:
      vars: ${{ needs.setvars.outputs.vars }}
    secrets: inherit
