name: Desktop
on:
  workflow_call:
    inputs:
      vars:
        required: true
        type: string

env:
  # prefer ipv4 stack (see https://nodejs.org/api/cli.html#--dns-result-orderorder)
  NODE_OPTIONS: "--dns-result-order=ipv4first"

jobs:
  build-desktop:
    if: ${{ fromJSON(inputs.vars).desktopMatrix[0] != null }}
    strategy:
      matrix:
        include: ${{ fromJSON(inputs.vars).desktopMatrix }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: desktop
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: "/desktop/.nvmrc"
      - name: Restore backend NPM cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ github.run_id }}
          restore-keys: |
            npm-
      - name: Install desktop dependencies
        run: npm ci

      - name: Install Linux packaging deps (Linux only)
        if: ${{ matrix.platform == 'linux' }}
        run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev libnss3 libxss1 libasound2t64 fakeroot rpm

      - name: Download Backend Artifact
        uses: actions/download-artifact@v4
        with:
          name: backend
          path: backend/dist

      - name: Download UI Artifact
        uses: actions/download-artifact@v4
        with:
          name: ui
          path: ui/dist

      - name: Prepare and Build Desktop
        run: |
          # Remove conflicting config file from backend artifact to avoid EEXIST error
          rm -f ../backend/dist/config/users.json
          npm run convert-icon
          npm run build

      - name: Build Electron App
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run ${{ matrix.buildScript }}

      - name: Upload Desktop artifact
        uses: actions/upload-artifact@v4
        with:
          name: desktop-${{ matrix.platform }}
          path: |
            desktop/dist-build/**
          retention-days: 1
