name: MCP
on:
  workflow_call:
    inputs:
      vars:
        required: true
        type: string

jobs:
  build-mcp:
    if: ${{ fromJSON(inputs.vars).mcpComponents != 0 || startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mcp
    steps:
      - uses: actions/checkout@v7
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: "/mcp/.nvmrc"
      - name: Restore backend NPM cache
        uses: actions/cache@v6
        with:
          path: ~/.npm
          key: npm-${{ github.run_id }}
          restore-keys: |
            npm-
      - name: Install MCP dependencies
        run: npm ci

      - name: Test MCP server
        run: npm run test

      - name: Build MCP server
        run: npm run build

      - name: Upload MCP artifact
        uses: actions/upload-artifact@v7
        with:
          name: mcp
          path: mcp/dist
          retention-days: 1
